// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeStop.Infra.Database;

namespace WeStop.Infra.Migrations
{
    [DbContext(typeof(WeStopSqlServerDbContext))]
    [Migration("20190507130349_gameroom_player_table")]
    partial class gameroom_player_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeStop.Domain.GameRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("AvailableLetters")
                        .IsRequired()
                        .HasColumnName("available_letters")
                        .HasMaxLength(52);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Expiration")
                        .HasColumnName("expiraton_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(15);

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnName("number_of_players");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnName("number_of_rounds");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("status")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Themes")
                        .IsRequired()
                        .HasColumnName("themes")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("gameroom");
                });

            modelBuilder.Entity("WeStop.Domain.GameRoomPlayer", b =>
                {
                    b.Property<Guid>("GameRoomId")
                        .HasColumnName("gameroom_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnName("player_id");

                    b.HasKey("GameRoomId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("gameroom_player");
                });

            modelBuilder.Entity("WeStop.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(35);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("player");
                });

            modelBuilder.Entity("WeStop.Domain.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("theme");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce9efc4d-0302-4f15-913d-b3a7082aed3e"),
                            Name = "Nome"
                        },
                        new
                        {
                            Id = new Guid("2889c013-cf0f-4789-84a8-64bb35ad3806"),
                            Name = "Sobrenome"
                        },
                        new
                        {
                            Id = new Guid("f19aac0c-a945-48e4-a132-53a7366861bb"),
                            Name = "CEP"
                        },
                        new
                        {
                            Id = new Guid("dcc57e28-9240-473b-8788-82743b404050"),
                            Name = "FDS"
                        },
                        new
                        {
                            Id = new Guid("4c27fc4e-758b-4722-ac67-2899462cb888"),
                            Name = "Carro"
                        },
                        new
                        {
                            Id = new Guid("170b4872-9145-48e1-bc18-502fd1e9c4fc"),
                            Name = "Marca"
                        },
                        new
                        {
                            Id = new Guid("8e4cd5ff-330f-44e5-8ade-ba70644422ef"),
                            Name = "Objeto"
                        },
                        new
                        {
                            Id = new Guid("b3525d81-d94e-4429-9b75-33717dbb3b68"),
                            Name = "Cor"
                        },
                        new
                        {
                            Id = new Guid("5f21b1b2-6213-4560-bcf3-42b31fe45bc0"),
                            Name = "Fruta"
                        });
                });

            modelBuilder.Entity("WeStop.Domain.GameRoomPlayer", b =>
                {
                    b.HasOne("WeStop.Domain.GameRoom", "GameRoom")
                        .WithMany("GameRoomPlayers")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeStop.Domain.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
